# Generated by Django 5.2.4 on 2025-08-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0009_alter_workoutscript_duration_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutscript',
            name='duration_minutes',
            field=models.FloatField(help_text='Duration in MM.SS format (e.g., 3.30 = 3 minutes 30 seconds, 10.45 = 10 minutes 45 seconds)'),
        ),
    ]
