# Generated by Django 5.2.4 on 2025-11-29 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0010_alter_workoutscript_duration_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='workouttemplate',
            name='allow_multiple_selections',
            field=models.BooleanField(default=False, help_text='Allow selecting multiple scripts from this category in sequence'),
        ),
        migrations.AddField(
            model_name='workouttemplate',
            name='max_selections',
            field=models.IntegerField(default=1, help_text='Maximum number of scripts to select (only used if allow_multiple_selections is True)'),
        ),
        migrations.AddField(
            model_name='workouttemplate',
            name='min_selections',
            field=models.IntegerField(default=1, help_text='Minimum number of scripts to select (only used if allow_multiple_selections is True)'),
        ),
    ]
