# Generated by Django 5.2.4 on 2025-12-17 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0011_workouttemplate_allow_multiple_selections_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutscript',
            name='audio_duration_en',
            field=models.FloatField(blank=True, help_text='Duration of English audio in minutes', null=True),
        ),
        migrations.AddField(
            model_name='workoutscript',
            name='audio_duration_nl',
            field=models.FloatField(blank=True, help_text='Duration of Dutch audio in minutes', null=True),
        ),
        migrations.AddField(
            model_name='workoutscript',
            name='audio_en',
            field=models.FileField(blank=True, help_text='English audio recording for this script', null=True, upload_to='workout_audio/en/'),
        ),
        migrations.AddField(
            model_name='workoutscript',
            name='audio_nl',
            field=models.FileField(blank=True, help_text='Dutch audio recording for this script', null=True, upload_to='workout_audio/nl/'),
        ),
        migrations.AlterField(
            model_name='workoutscript',
            name='duration_minutes',
            field=models.FloatField(help_text='How long this takes to speak in minutes'),
        ),
    ]
