# Generated by Django 5.2.4 on 2025-12-17 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0003_alter_workoutsession_goal'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('nl', 'Dutch'), ('en', 'English')], help_text='Language of this audio playlist', max_length=2)),
                ('total_duration', models.FloatField(help_text='Total duration including pauses in minutes')),
                ('segment_count', models.IntegerField(help_text='Total number of segments in playlist')),
                ('available_segment_count', models.IntegerField(help_text='Number of segments with available audio')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workout_session', models.ForeignKey(help_text='Which workout session this audio playlist belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='audio_playlists', to='generator.workoutsession')),
            ],
            options={
                'verbose_name': 'Audio Playlist',
                'verbose_name_plural': 'Audio Playlists',
                'ordering': ['-created_at'],
                'unique_together': {('workout_session', 'language')},
            },
        ),
        migrations.CreateModel(
            name='AudioSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_order', models.IntegerField(help_text='Order in the playlist (matches SessionScript order)')),
                ('audio_file', models.FileField(blank=True, help_text='Reference to the audio file', null=True, upload_to='merged_audio/')),
                ('duration', models.FloatField(blank=True, help_text='Duration of this audio segment in minutes', null=True)),
                ('is_available', models.BooleanField(default=False, help_text='Whether audio is available for this segment')),
                ('pause_after', models.FloatField(default=2.0, help_text='Pause duration after this segment in seconds')),
                ('audio_playlist', models.ForeignKey(help_text='Which audio playlist this segment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='generator.audioplaylist')),
                ('session_script', models.ForeignKey(help_text='The workout script this audio represents', on_delete=django.db.models.deletion.CASCADE, to='generator.sessionscript')),
            ],
            options={
                'verbose_name': 'Audio Segment',
                'verbose_name_plural': 'Audio Segments',
                'ordering': ['sequence_order'],
                'unique_together': {('audio_playlist', 'sequence_order')},
            },
        ),
    ]
