# Generated by Django 5.2.4 on 2025-12-19 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0004_add_audio_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='audioplaylist',
            name='merged_at',
            field=models.DateTimeField(blank=True, help_text='When the audio was last merged', null=True),
        ),
        migrations.AddField(
            model_name='audioplaylist',
            name='merged_audio_file',
            field=models.FileField(blank=True, help_text='Merged audio file (all segments combined)', null=True, upload_to='merged_audio/'),
        ),
    ]
